# Generated by Django 4.0.5 on 2022-08-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=120)),
                ('vehicle_model', models.CharField(max_length=150)),
                ('vehicle_description', models.TextField()),
            ],
        ),
    ]
